spring:
  application:
    name: fbai
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fbai}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    secret: ${JWT_SECRET}
    token-validity-time: ${JWT_TOKEN_VALIDITY_TIME}
